// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as META_BOARD_ADDR,
    BYTECODE_HASH as META_BOARD_HASH
} from "../generated/candidate/MetaBoard.sol";

/// @title LibMetaBoardDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `MetaBoard`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibMetaBoardDeploy {
    address constant META_BOARD_DEPLOYED_ADDRESS = META_BOARD_ADDR;
    bytes32 constant META_BOARD_DEPLOYED_CODEHASH = META_BOARD_HASH;
}
